### ISSUE TITLE
db hints

### ISSUE THREAD

**Issue by vitaly-t** [jameshy/pg-job-queue#8]
from here: https://github.com/jameshy/pg-job-queue/blob/master/lib/index.js

this code doesn't do anything useful:

``` js
function connect(connectionString) {
    db = pgp(connectionString)
    return db.connect()
}
```

if you want to diagnose the connection, see: http://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app

Other than that, you should just initialize `db` instance globally once, and that's it.

for this code:

``` js
function installSchema() {
    var schema = path.join(__dirname, 'schema.sql')
    var qf = new pgp.QueryFile(schema)
    return db.none(qf)
}
```

Type `QueryFile` is meant to be created once per file, when starting the application, as [per documentation](http://vitaly-t.github.io/pg-promise/QueryFile.html), not dynamically later. That's because it works like permanent binding to the file.

for this code:

``` js
   return db.tx(function(t) {
        return t.oneOrNone('SELECT * FROM pending_jobs(1, $1)', formatArray(types))
    }).then(function(result) {
```

it doesn't make sense using a transaction for a single select. It does nothing useful in such context, only slows down the code.

**Comment by jameshy** [comment]
Amazing, thanks Vitaly !

**Comment by jameshy** [comment]
Hopefully fixed!
